### PR TITLE
added search api

### PR DESCRIPTION
**Pull request by LesterCodingMaster**
Changed app.JS also I had to change a few things to update search API.
I had a hard time importing or pulling the new file and merging with mine for some reason, so what I had to do is clone it again, and start from scratch so I kept my old project open and copied what I had originally and put in here so it shows a lot of stuff is changed but it's not that much.
But check this out and see if it looks

### CODE REVIEW

**Review by Ficklin — CHANGES_REQUESTED** [review]
Hi Joe, It looks like you don't have the latest version of the main backend dev. Carlito added Cor coding to the App.ts that your file is missing. Please update branch and resubmit.  Otherwise, the code looks good to go. Thanks!

**Comment by LesterCodingMaster** [comment]
Everything is working fine on my end check Slack for a video but please review this and see if we can merge it and have the Everything is working fine on my end check Slack for a video but please review this and see if we can merge it and have the dev branch up-to-date

**Review by Carlito-Pedida — APPROVED** [review]
The comparison looks good to me. I don't see any conflicts at all. I wonder if the conflict message was from the first pull request.

**Review by Carlito-Pedida — APPROVED** [review]
checked

**Review by Ficklin — APPROVED** [review]
Team troubleshooting DS file issue.

**Pull request merged**
